---

- hosts: localhost
  connection: local
  no_log: True
  vars:
    port: "{{ lookup('env', 'PORT') | default('8443') }}"
    ssl: "{{ lookup('env', 'SSL_ENABLED') | default(false) | bool }}"
    ssl_cert: "{{ lookup('env', 'SSL_CERT') | default('') }}"
    ssl_key: "{{ lookup('env', 'SSL_KEY') | default('') }}"
  tasks:
  - command: awk '/^nameserver/{print $2}' /etc/resolv.conf
    register: resolver
  - template:
      src: vars.yml.j2
      dest: vars.yml

- hosts: localhost
  connection: local
  no_log: True
  vars_files:
  - vars.yml
  tasks:
  - template:
      src: nginx.conf.j2
      dest: /app/nginx.conf
  - copy:
      content: "{{ nginx.ssl.key | regex_replace('\\\\n', '\n') }}"
      dest: /app/ssl.key
      mode: 0600
    when: nginx.ssl.enabled
  - copy:
      content: "{{ nginx.ssl.cert | regex_replace('\\\\n', '\n') }}"
      dest: /app/ssl.crt
      mode: 0644
    when: nginx.ssl.enabled
